# This GitHub Action runs only on pushes to main. It can be used by tag
# protection rules to ensure that tags may only be pushed if their
# corresponding commit was first pushed to main.
name: Merged to main
on:
  push:
    branches:
      - main
jobs:
